### PR TITLE
Bump GCC to 11.2

### PR DESCRIPTION
**Pull request by MichaelLettrich**
The last PR contained incomplete data, I seemed to not have cleanly committed all changes.

### CODE REVIEW

**Comment by ktf** [comment]
There is some instructions on how to do that  in the alisw/alidist README.

**Comment by MichaelLettrich** [comment]
Sorry, I didn't know that. I'll check it.

**Comment by MichaelLettrich** [comment]
yes, I used `git commit -am <message>` for this one. I was convinced that I have done it before as well but apparently it was not the case. sorry for the mistake.

**Comment by MichaelLettrich** [comment]
This is hopefully better now and can be merged?

**Comment by ktf** [comment]
There are conflicts...

**Comment by MichaelLettrich** [comment]
ok this is wired. Let me recreate the branch and fix it up. Something here went terribly wrong.

**Pull request closed without merging**
